[package]
name = "ftp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
useful = {path = "../useful"}
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7" # Optional for framed communication
tokio-rustls = "0.26.0"
rustls = "0.23.18"